"""Deterministic WAF response fingerprints and weighted classification."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Mapping


VENDOR_PATTERNS = {
    "Cloudflare": (
        ("cf-ray", "cf-cache-status", "__cf_bm"),
        ("cloudflare ray id", "error 1020", "cdn-cgi/challenge-platform",
         "attention required! | cloudflare", "sorry, you have been blocked"),
    ),
    "AWS WAF": (
        ("x-amzn-requestid", "x-amzn-trace-id", "x-amz-cf-id"),
        ("request blocked", "generated by cloudfront",
         "the request could not be satisfied"),
    ),
    "Akamai": (
        ("x-akamai", "akamai-origin-hop"),
        ("akamaighost", "reference #"),
    ),
    "Imperva / Incapsula": (
        ("x-iinfo", "incap_ses", "visid_incap"),
        ("incapsula incident", "_incapsula_resource", "incident id"),
    ),
    "F5 BIG-IP ASM": (
        ("x-cnection",),
        ("the requested url was rejected", "support id"),
    ),
    "ModSecurity": (
        ("x-modsecurity", "x-mod-security"),
        ("modsecurity", "mod_security", "not acceptable"),
    ),
    "Sucuri": (
        ("x-sucuri-id", "x-sucuri-cache"),
        ("sucuri website firewall", "access denied - sucuri"),
    ),
}

CHALLENGE_PATTERNS = (
    "cf_chl_opt", "challenge-form", "jschl_vc", "checking your browser",
    "please enable javascript", "recaptcha/api.js", "hcaptcha.com",
    "challenges.cloudflare.com", "_px3", "px-captcha", "datadome",
)
BLOCK_TITLE_RE = re.compile(
    r"(?is)<title[^>]*>[^<]*(access denied|request rejected|blocked|forbidden|"
    r"attention required|security violation|not acceptable)"
)
BUSINESS_SIGNAL_RE = re.compile(
    r"(?i)(csrf[_-]?token|user[_-]?id|access[_-]?token|refresh[_-]?token|"
    r"session[_-]?id|<form\b|\"[a-z_][a-z0-9_]*\"\s*:)"
)
LOG_ID_PATTERNS = (
    re.compile(r"(?i)(?:cf-ray|cloudflare\s+ray\s+id)[:\s#=]+([0-9a-f-]{12,30})"),
    re.compile(r"(?i)support\s+id[:\s#=]+([0-9]{8,30})"),
    re.compile(r"(?i)incident\s+id[:\s#=]+([a-z0-9-]{6,40})"),
    re.compile(
        r"(?i)(?:request|trace|event|reference|error)\s*(?:id|#)"
        r"[:\s#=]+([a-z0-9_.-]{6,40})"
    ),
)


def _headers_text(headers: Mapping | None) -> str:
    return "\n".join(
        "{}: {}".format(str(key).lower(), str(value).lower())
        for key, value in (headers or {}).items()
    )


def _length_similarity(left: int, right: int) -> float:
    if left <= 0 or right <= 0:
        return 0.0
    return min(left, right) / max(left, right)


@dataclass(frozen=True)
class ResponseFingerprint:
    status_code: int
    body_length: int
    body_sha256: str
    vendor: str
    challenge: bool
    block_title: bool
    business_signal: bool
    log_id: str | None
    retry_after: bool

    @classmethod
    def build(
        cls,
        status_code: int,
        body: str = "",
        headers: Mapping | None = None,
    ) -> "ResponseFingerprint":
        content = str(body or "")
        lower_body = content.lower()
        header_text = _headers_text(headers)
        best_vendor = ""
        best_hits = 0
        for vendor, (header_patterns, body_patterns) in VENDOR_PATTERNS.items():
            hits = sum(pattern in header_text for pattern in header_patterns)
            hits += sum(pattern in lower_body for pattern in body_patterns)
            if hits > best_hits:
                best_hits = hits
                best_vendor = vendor
        log_id = None
        combined = header_text + "\n" + content[:16000]
        for pattern in LOG_ID_PATTERNS:
            match = pattern.search(combined)
            if match:
                log_id = match.group(1)
                break
        return cls(
            status_code=int(status_code or 0),
            body_length=len(content.encode("utf-8", errors="replace")),
            body_sha256=hashlib.sha256(
                content.encode("utf-8", errors="replace")
            ).hexdigest(),
            vendor=best_vendor,
            challenge=any(pattern in lower_body for pattern in CHALLENGE_PATTERNS),
            block_title=bool(BLOCK_TITLE_RE.search(content[:8192])),
            business_signal=bool(BUSINESS_SIGNAL_RE.search(content[:16000])),
            log_id=log_id,
            retry_after="retry-after:" in header_text,
        )


@dataclass(frozen=True)
class ResponseBaseline:
    normal: ResponseFingerprint | None = None
    blocked: ResponseFingerprint | None = None


def classify_response(
    fingerprint: ResponseFingerprint,
    baseline: ResponseBaseline | None = None,
) -> dict:
    """Return a transparent weighted verdict suitable for throttle decisions."""
    baseline = baseline or ResponseBaseline()
    score = 0
    reasons: list[str] = []

    if fingerprint.status_code == 429:
        score += 55
        reasons.append("HTTP 429 rate limit")
    elif fingerprint.status_code in {503, 521, 522, 524}:
        score += 30
        reasons.append("edge/challenge status")
    elif fingerprint.status_code == 403:
        score += 18
        reasons.append("HTTP 403")

    if fingerprint.vendor:
        score += 35
        reasons.append("{} signature".format(fingerprint.vendor))
    if fingerprint.challenge:
        score += 50
        reasons.append("browser challenge markers")
    if fingerprint.block_title:
        score += 30
        reasons.append("block-page title")
    if fingerprint.log_id:
        score += 12
        reasons.append("WAF request/reference ID")
    if fingerprint.business_signal:
        score -= 15
        reasons.append("application business content")
    if fingerprint.retry_after:
        score += 35
        reasons.append("Retry-After header")

    if baseline.blocked:
        if fingerprint.body_sha256 == baseline.blocked.body_sha256:
            score += 45
            reasons.append("exact block-baseline body")
        elif _length_similarity(
            fingerprint.body_length, baseline.blocked.body_length
        ) >= 0.92:
            score += 20
            reasons.append("block-baseline length match")
        if fingerprint.status_code == baseline.blocked.status_code:
            score += 8

    if baseline.normal:
        if fingerprint.body_sha256 == baseline.normal.body_sha256:
            score -= 45
            reasons.append("exact normal-baseline body")
        elif _length_similarity(
            fingerprint.body_length, baseline.normal.body_length
        ) >= 0.92:
            score -= 18
            reasons.append("normal-baseline length match")
        if (
            fingerprint.status_code == baseline.normal.status_code
            and fingerprint.business_signal
        ):
            score -= 8

    score = max(0, min(100, score))
    if fingerprint.challenge:
        classification = "challenge"
    elif fingerprint.status_code == 429:
        classification = "rate_limit"
    elif score >= 50:
        classification = "waf_block"
    elif score >= 25:
        classification = "ambiguous"
    else:
        classification = "application_response"

    return {
        "classification": classification,
        "score": score,
        "is_block": classification in {"challenge", "rate_limit", "waf_block"},
        "vendor": fingerprint.vendor or "Unknown",
        "log_id": fingerprint.log_id,
        "reasons": reasons,
        "status_code": fingerprint.status_code,
        "body_length": fingerprint.body_length,
    }
