"""
waf_engine.py — WAF Fingerprinting & Adaptive Traffic Throttle
Runs BEFORE Phase 2 to identify WAF vendor and configure evasion strategy.
Also provides the global throttle manager used by all hunt workers.
"""

import asyncio
import re
import time
import httpx
from collections import defaultdict, deque
from email.utils import parsedate_to_datetime
from typing import Callable, Optional
from urllib.parse import urlparse
from scope_policy import scope_policy
from waf_response_intelligence import (
    ResponseBaseline,
    ResponseFingerprint,
    classify_response,
)

# ── WAF signature database ────────────────────────────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
        "body":     ["Cloudflare", "cloudflare", "1020", "Error 1006", "cf-error-details"],
        "status":   [403, 503],
        "server":   ["cloudflare"],
    },
    "AWS WAF": {
        "headers":  ["x-amzn-requestid", "x-amz-cf-id", "x-amz-id"],
        "body":     ["AWS WAF", "Request blocked", "aws-waf"],
        "status":   [403, 405],
        "server":   [],
    },
    "Akamai": {
        "headers":  ["x-akamai-transformed", "akamai-origin-hop", "x-check-cacheable"],
        "body":     ["AkamaiGHost", "Reference #", "Access Denied"],
        "status":   [403],
        "server":   ["AkamaiGHost"],
    },
    "Imperva / Incapsula": {
        "headers":  ["x-iinfo", "x-cdn"],
        "body":     ["Incapsula incident", "_Incapsula_Resource", "incap_ses"],
        "status":   [403],
        "server":   ["Incapsula"],
    },
    "ModSecurity": {
        "headers":  ["x-modsecurity", "x-mod-security"],
        "body":     ["ModSecurity", "mod_security", "NOYB", "Not Acceptable"],
        "status":   [406, 403],
        "server":   ["mod_security", "modsecurity"],
    },
    "Sucuri": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "body":     ["Sucuri Website Firewall", "Access Denied - Sucuri"],
        "status":   [403],
        "server":   ["Sucuri/Cloudproxy"],
    },
    "F5 BIG-IP ASM": {
        "headers":  ["x-cnection", "ts"],
        "body":     ["The requested URL was rejected", "BIG-IP", "support ID"],
        "status":   [403],
        "server":   ["BigIP"],
    },
    "Barracuda": {
        "headers":  ["barra_counter_session"],
        "body":     ["Barracuda Web Application Firewall", "barra_"],
        "status":   [403],
        "server":   [],
    },
    "Fortinet FortiWeb": {
        "headers":  ["x-waf-event-info"],
        "body":     ["FortiWeb", "Application access is blocked"],
        "status":   [403],
        "server":   ["FortiWeb"],
    },
    "Wordfence": {
        "headers":  [],
        "body":     ["Wordfence", "generated by Wordfence", "Your access to this site"],
        "status":   [403],
        "server":   [],
    },
    "Nginx Rate Limit": {
        "headers":  [],
        "body":     ["503 Service Temporarily Unavailable", "nginx"],
        "status":   [429, 503],
        "server":   ["nginx"],
    },
}

# ── Probe payloads (benign-malicious — triggers WAF without real impact) ──────

WAF_PROBE_PAYLOADS = [
    "/?x=<script>alert(1)</script>",
    "/?x=' OR 1=1--",
    "/?x=../../../etc/passwd",
    "/?x=;cat /etc/passwd",
]

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Accept":     "text/html,application/json,*/*",
}


# ── WAF detector ─────────────────────────────────────────────────────────────

async def fingerprint_waf(base_url: str, log: Callable) -> dict:
    """
    Send malicious probes to a non-existent endpoint and analyse the block screen.
    Returns WAF info dict: {detected: bool, vendor: str, strategy: str, block_status: int}
    """
    ok, reason = scope_policy.validate_target(base_url, action="scan")
    if not ok:
        await log("[WAF] Skipped by ScopePolicy: {}".format(reason))
        return {"detected": False, "vendor": "ScopePolicy", "confidence": 0,
                "strategy": "passive_only", "blocked": True}
    result = {
        "detected":     False,
        "vendor":       "Unknown",
        "strategy":     "normal",   # passive_only | conservative | normal | intensive_authorized
        "block_status": 0,
        "block_body":   "",
        "confidence":   0,
    }

    await log("[WAF] Fingerprinting WAF on {}".format(base_url))

    # First probe: completely non-existent endpoint (establishes 404 baseline)
    base = base_url.rstrip("/")
    try:
        async with httpx.AsyncClient(
            headers=HEADERS, verify=False,
            follow_redirects=False, timeout=10
        ) as client:
            # Baseline — clean request to non-existent path
            r_clean = await client.get(
                base + "/burpollama-nonexistent-8x7k2",
                headers=HEADERS
            )
            clean_status = r_clean.status_code
            clean_body   = r_clean.text[:500]

            # Now send malicious probe
            for probe in WAF_PROBE_PAYLOADS:
                r_waf = await client.get(base + probe, headers=HEADERS)

                # If response differs from clean → WAF likely intercepted
                if r_waf.status_code != clean_status or r_waf.text[:200] != clean_body[:200]:
                    vendor, confidence = _identify_vendor(r_waf)
                    if confidence > 0:
                        result.update({
                            "detected":     True,
                            "vendor":       vendor,
                            "block_status": r_waf.status_code,
                            "block_body":   r_waf.text[:300],
                            "confidence":   confidence,
                            "strategy":     _pick_strategy(vendor),
                        })
                        await log("[WAF] ⚠ Detected: {} (confidence {}%) — using '{}' strategy".format(
                            vendor, confidence, result["strategy"]
                        ))
                        return result

    except Exception as e:
        await log("[WAF] Probe error: {}".format(e))

    await log("[WAF] No WAF detected — using normal strategy")
    return result


def _identify_vendor(response: httpx.Response) -> tuple[str, int]:
    """Match a response against WAF signatures. Returns (vendor, confidence 0-100)."""
    resp_headers = {k.lower(): v.lower() for k, v in response.headers.items()}
    body         = response.text.lower()
    server       = resp_headers.get("server", "")
    best_vendor  = "Unknown"
    best_score   = 0

    for vendor, sigs in WAF_SIGNATURES.items():
        score = 0

        # Header matches (weight 3 each)
        for h in sigs["headers"]:
            if h.lower() in resp_headers:
                score += 3

        # Body matches (weight 2 each)
        for b in sigs["body"]:
            if b.lower() in body:
                score += 2

        # Server header (weight 4)
        for s in sigs["server"]:
            if s.lower() in server:
                score += 4

        # Status code match (weight 1)
        if response.status_code in sigs["status"]:
            score += 1

        if score > best_score:
            best_score  = score
            best_vendor = vendor

    # Convert score to confidence %
    confidence = min(95, best_score * 12) if best_score > 0 else 0
    return best_vendor, confidence


def _pick_strategy(vendor: str) -> str:
    """Pick the appropriate authorized scan strategy based on WAF vendor."""
    slow_waf     = {"ModSecurity", "F5 BIG-IP ASM", "Barracuda", "Fortinet FortiWeb"}
    conservative_waf  = {"Cloudflare", "Akamai", "Imperva / Incapsula"}
    standard_waf = {"Nginx Rate Limit", "Wordfence"}

    if vendor in slow_waf:
        return "conservative"
    elif vendor in conservative_waf:
        return "conservative"
    elif vendor in standard_waf:
        return "normal"
    return "normal"


# ── Adaptive throttle manager ─────────────────────────────────────────────────

class ThrottleManager:
    """
    Global traffic monitor for all hunt workers.
    When any worker hits a WAF block or rate limit, all workers pause
    and the request rate is backed off exponentially.

    Usage:
        throttle = ThrottleManager()
        async with throttle.gate():
            response = await client.get(url)
            throttle.record(response.status_code, response.text)
    """

    WAF_BODY_INDICATORS = [
        "cloudflare", "incapsula", "sucuri", "barracuda",
        "access denied", "blocked", "bot", "captcha",
        "security check", "ddos", "unusual activity",
    ]

    def __init__(self):
        self._lock               = asyncio.Lock()
        self._paused             = False
        self._backoff            = 0.5
        self._backoff_mult       = 1.0
        self._max_mult           = 16.0
        self._last_block         = 0.0
        self._recovery_secs      = 45
        self._total_blocks       = 0
        self._broadcast_fn       = None
        # v3.3: HOST_DEAD_WAF threshold
        self._consecutive_blocks = 0
        self._max_consecutive    = 10    # mark host dead after this many sequential blocks
        self._host_dead          = False
        self._host_counters      = defaultdict(lambda: {
            "requests": 0,
            "blocks": 0,
            "window": deque(maxlen=500),
            "last_block_reason": "",
            "cooldown_until": 0.0,
        })
        self._global_window      = deque(maxlen=2000)
        self._last_block_reason  = ""
        self._cooldown_until     = 0.0
        self._cooldown_reason    = ""
        self._smart_mode         = True
        self._response_baselines: dict[str, ResponseBaseline] = {}
        self._last_classification: dict[str, dict] = {}

    def set_broadcast(self, fn):
        self._broadcast_fn = fn

    @property
    def host_dead(self) -> bool:
        return self._host_dead

    @property
    def current_delay(self) -> float:
        return self._backoff * self._backoff_mult

    def _host(self, url: str = "") -> str:
        try:
            return urlparse(url).netloc or "unknown"
        except Exception:
            return "unknown"

    def _retry_after_seconds(self, headers: dict | None = None) -> float:
        if not headers:
            return 0.0
        value = ""
        for k, v in headers.items():
            if str(k).lower() == "retry-after":
                value = str(v).strip()
                break
        if not value:
            return 0.0
        try:
            return max(0.0, min(300.0, float(value)))
        except ValueError:
            try:
                return max(0.0, min(300.0, parsedate_to_datetime(value).timestamp() - time.time()))
            except Exception:
                return 0.0

    def _reason_for_block(self, status: int, body: str = "", headers: dict | None = None) -> str:
        retry = self._retry_after_seconds(headers)
        body_lower = (body or "").lower()
        if retry:
            return "Server requested Retry-After {:.0f}s".format(retry)
        if status == 429:
            return "Rate limited with HTTP 429"
        if status == 403:
            return "Forbidden or WAF block with HTTP 403"
        if status == 503:
            return "Service unavailable or WAF challenge with HTTP 503"
        if status == 200 and any(c in body_lower for c in CHALLENGE_INDICATORS):
            return "WAF/challenge page detected"
        return "Target is blocking requests"

    def recommendation(self) -> str:
        if self._host_dead or self._consecutive_blocks >= 6 or self._backoff_mult >= 8:
            return "Target is blocking requests. Switch from Deep Authorized Scan to Bounty Scan or Safe Passive Scan."
        if self._consecutive_blocks >= 3 or self._backoff_mult >= 4:
            return "Target is showing blocking behavior. Prefer Bounty Scan or Safe Passive Scan."
        return "Throttle is healthy."

    def status(self) -> dict:
        now = time.monotonic()
        recent = [x for x in self._global_window if now - x[0] <= 60]
        recent_blocks = [x for x in recent if x[2]]
        host_stats = {}
        known_hosts = set(self._host_counters) | set(self._last_classification)
        for host in known_hosts:
            data = self._host_counters[host]
            window = list(data["window"])
            recent_host = [x for x in window if now - x[0] <= 60]
            recent_host_blocks = [x for x in recent_host if x[1]]
            host_stats[host] = {
                "requests": data["requests"],
                "blocks": data["blocks"],
                "requests_per_minute": len(recent_host),
                "block_rate": round((len(recent_host_blocks) / max(1, len(recent_host))) * 100, 1),
                "last_block_reason": data["last_block_reason"],
                "cooldown_remaining_secs": max(0, round(data["cooldown_until"] - now, 1)),
                "last_response_classification": self._last_classification.get(host, {}),
            }
        return {
            "smart_mode": self._smart_mode,
            "requests_per_minute": len(recent),
            "block_rate": round((len(recent_blocks) / max(1, len(recent))) * 100, 1),
            "last_block_reason": self._last_block_reason,
            "cooldown_active": now < self._cooldown_until,
            "cooldown_remaining_secs": max(0, round(self._cooldown_until - now, 1)),
            "cooldown_reason": self._cooldown_reason,
            "current_throttle_multiplier": self._backoff_mult,
            "current_delay": round(self.current_delay, 2),
            "total_blocks": self._total_blocks,
            "consecutive_blocks": self._consecutive_blocks,
            "host_dead": self._host_dead,
            "recommendation": self.recommendation(),
            "hosts": host_stats,
        }

    async def gate(self):
        """Async context manager — waits if throttled before proceeding."""
        return _ThrottleGate(self)

    async def _wait(self):
        """Wait the current throttle delay."""
        now = time.monotonic()
        if self._cooldown_until > now:
            await asyncio.sleep(max(0.0, self._cooldown_until - now))
        delay = self.current_delay
        if delay > 0.1:
            await asyncio.sleep(delay)

    async def record_request(self, url: str = ""):
        host = self._host(url)
        now = time.monotonic()
        async with self._lock:
            data = self._host_counters[host]
            data["requests"] += 1
            data["window"].append((now, False))
            self._global_window.append((now, host, False))

    async def record_block(self, status: int, body: str = "", url: str = "", headers: dict | None = None):
        """Call when a worker receives a block/rate-limit response."""
        import random as _rand
        async with self._lock:
            host = self._host(url)
            host_data = self._host_counters[host]
            self._total_blocks       += 1
            self._consecutive_blocks += 1
            self._last_block          = time.monotonic()
            self._backoff_mult        = min(self._max_mult, self._backoff_mult * 2)
            self._paused              = True
            classification = self._last_classification.get(host, {})
            if classification.get("is_block"):
                reason = "{} (score {}): {}".format(
                    str(classification.get("classification", "WAF block")).replace("_", " "),
                    classification.get("score", 0),
                    ", ".join(classification.get("reasons", [])[:3])
                    or self._reason_for_block(status, body, headers),
                )
            else:
                reason = self._reason_for_block(status, body, headers)
            self._last_block_reason = reason
            host_data["blocks"] += 1
            host_data["last_block_reason"] = reason
            marked = False
            for i in range(len(host_data["window"]) - 1, -1, -1):
                ts, blocked = host_data["window"][i]
                if not blocked and self._last_block - ts <= 10:
                    host_data["window"][i] = (ts, True)
                    marked = True
                    break
            global_marked = False
            for i in range(len(self._global_window) - 1, -1, -1):
                ts, h, blocked = self._global_window[i]
                if h == host and not blocked and self._last_block - ts <= 10:
                    self._global_window[i] = (ts, h, True)
                    global_marked = True
                    break
            if not marked:
                host_data["window"].append((self._last_block, True))
            if not global_marked:
                self._global_window.append((self._last_block, host, True))

            # v3.3: Jitter prevents thundering-herd re-requests after backoff
            retry_after = self._retry_after_seconds(headers)
            base_wait  = max(retry_after, min(30, self._backoff_mult * 2))
            if self._consecutive_blocks >= 3:
                base_wait = max(base_wait, min(120, 15 * (self._consecutive_blocks - 2)))
            jitter     = _rand.uniform(0, 1.0)
            pause_time = base_wait + jitter
            self._cooldown_until = max(self._cooldown_until, self._last_block + pause_time)
            self._cooldown_reason = reason
            host_data["cooldown_until"] = max(host_data["cooldown_until"], self._last_block + pause_time)

            print("[Throttle] BLOCK #{} (status={}) — pause {:.1f}s (mult={:.1f}x jitter={:.2f})".format(
                self._consecutive_blocks, status, pause_time,
                self._backoff_mult, jitter))

            # v3.3: HOST_DEAD_WAF — abort scan after _max_consecutive blocks
            if self._consecutive_blocks >= self._max_consecutive and not self._host_dead:
                self._host_dead = True
                dead_msg = (
                    "[Throttle] HOST_DEAD_WAF: {} consecutive blocks at max backoff. "
                    "Switching to passive-only mode.".format(self._consecutive_blocks)
                )
                print(dead_msg)
                if self._broadcast_fn:
                    await self._broadcast_fn({
                        "type":    "host_dead_waf",
                        "message": dead_msg,
                        "blocks":  self._consecutive_blocks,
                        "url":     url,
                    })

            if self._broadcast_fn:
                await self._broadcast_fn({
                    "type":    "throttle_warning",
                    "message": "Target is blocking requests",
                    "status":  status,
                    "delay":   pause_time,
                    "mult":    self._backoff_mult,
                    "jitter":  jitter,
                    "url":     url,
                    "host":    host,
                    "reason":  reason,
                    "recommendation": self.recommendation(),
                    "consecutive": self._consecutive_blocks,
                    "host_dead":   self._host_dead,
                    "status_snapshot": self.status(),
                })

            await asyncio.sleep(pause_time)
            self._paused = False

    async def maybe_recover(self):
        """Reduce multiplier if no blocks for recovery_secs."""
        async with self._lock:
            if (time.monotonic() - self._last_block > self._recovery_secs
                    and self._backoff_mult > 1.0):
                self._backoff_mult       = max(1.0, self._backoff_mult / 2)
                self._consecutive_blocks = 0   # reset on recovery
                self._cooldown_reason    = ""

    def calibrate_responses(
        self,
        url: str,
        *,
        normal_status: int,
        normal_body: str,
        normal_headers: dict | None = None,
        block_status: int | None = None,
        block_body: str = "",
        block_headers: dict | None = None,
    ) -> None:
        host = self._host(url)
        self._response_baselines[host] = ResponseBaseline(
            normal=ResponseFingerprint.build(
                normal_status, normal_body[:16000], normal_headers
            ),
            blocked=(
                ResponseFingerprint.build(
                    int(block_status), block_body[:16000], block_headers
                )
                if block_status is not None
                else None
            ),
        )

    def classify_response(
        self,
        status: int,
        body: str = "",
        headers: dict | None = None,
        url: str = "",
    ) -> dict:
        host = self._host(url)
        result = classify_response(
            ResponseFingerprint.build(status, body, headers),
            self._response_baselines.get(host),
        )
        self._last_classification[host] = result
        return result

    def is_block_response(
        self,
        status: int,
        body: str = "",
        headers: dict | None = None,
        url: str = "",
    ) -> bool:
        """Classify WAF blocks without treating every application 403 as one."""
        return bool(
            self.classify_response(status, body, headers, url).get("is_block")
        )

    async def record_network_error(self, url: str = ""):
        async with self._lock:
            import random as _rand
            wait = min(8.0, self._backoff * self._backoff_mult) + _rand.uniform(0, 0.5)
            self._last_block_reason = "Network error; retrying conservatively"
        await asyncio.sleep(wait)


class _ThrottleGate:
    """Async context manager returned by ThrottleManager.gate()"""
    def __init__(self, mgr: ThrottleManager):
        self._mgr = mgr

    async def __aenter__(self):
        # Wait if paused
        while self._mgr._paused:
            await asyncio.sleep(0.5)
        # Apply current delay
        await self._mgr._wait()
        await self._mgr.maybe_recover()
        return self

    async def __aexit__(self, *args):
        pass


# Global singleton — imported by hunt_engine and main
throttle = ThrottleManager()


# ── Challenge page detection (v3.3) ───────────────────────────────────────────
# Modern WAFs return HTTP 200 with a JS challenge or CAPTCHA instead of 403.
# If the hunt engine receives these it may mistake the challenge HTML for a
# real reflection or structural change, producing false positives.

CHALLENGE_INDICATORS = [
    # Cloudflare challenge / CAPTCHA variants
    "cf_chl_opt", "challenge-form", "jschl_vc", "jschl_answer",
    "__cf_chl_captcha_tk__", "__cf_chl_f_tk__",
    "cf-please-wait", "cf_chl_prog",
    # Generic reCAPTCHA / hCaptcha / Turnstile
    "recaptcha/api.js", "hcaptcha.com", "challenges.cloudflare.com",
    # Akamai Bot Manager
    "_abck=", "ak_bmsc", "bm_sz",
    # Imperva / Incapsula
    "incap_ses", "visid_incap",
    # PerimeterX / Human Security
    "_px3", "px-captcha",
    # Generic JS challenge patterns
    "document.cookie", "location.reload", "setTimeout(", "setInterval(",
    # DataDome
    "datadome", "dd_referrer",
]

_CHALLENGE_SCRIPT_RE = re.compile(
    r'<script[^>]*>[^<]{0,200}(document\.cookie\s*=|location\.href\s*=|'
    r'setTimeout\s*\(|challenge)',
    re.IGNORECASE | re.DOTALL
)


def is_challenge_page(response: httpx.Response) -> bool:
    """
    Detect a CAPTCHA or JavaScript challenge page disguised as HTTP 200.
    Called by hunt workers before processing any 200 response body.
    """
    if response.status_code != 200:
        return False
    body = response.text
    body_lower = body.lower()
    # Check keyword indicators
    if any(ind.lower() in body_lower for ind in CHALLENGE_INDICATORS):
        return True
    # Check for inline JS challenge scripts
    if _CHALLENGE_SCRIPT_RE.search(body):
        return True
    return False


# ── Benign probes for early WAF detection (v3.3) ─────────────────────────────
# Sent BEFORE blunt attack payloads to detect WAF presence without raising
# the target's threat score or triggering IP-level captcha challenges.

BENIGN_ANOMALY_PROBES = [
    # Non-standard HTTP method — many WAFs respond with 405 + vendor header
    {
        "method":  "PROPFIND",
        "path":    "/",
        "headers": {},
    },
    # Oversized Accept header — triggers header inspection without looking malicious
    {
        "method":  "GET",
        "path":    "/",
        "headers": {"Accept": "text/html, " + ("a/b, " * 150)},
    },
    # Unknown HTTP method — probes method validation without attack signatures
    {
        "method":  "BLKBURP",
        "path":    "/",
        "headers": {},
    },
    # Invalid Transfer-Encoding — triggers protocol normalization layer
    {
        "method":  "GET",
        "path":    "/",
        "headers": {"Transfer-Encoding": "xchunked"},
    },
]


async def fingerprint_waf_v2(base_url: str, log: Callable) -> dict:
    """
    v3.3 Two-stage WAF fingerprinting.

    Stage 1 — Benign anomaly probes (low noise):
      Uses non-standard methods and oversized headers to detect WAF presence
      without triggering IP threat escalation or CAPTCHA issuance.
      If Stage 1 detects a WAF with high confidence, skip Stage 2.

    Stage 2 — Malicious signature probes (only if Stage 1 inconclusive):
      Fires traditional attack payloads ('../', SQLi, XSS) to confirm vendor
      and extract block page signature.

    Returns full WAF info dict including challenge_detected flag.
    """
    ok, reason = scope_policy.validate_target(base_url, action="scan")
    if not ok:
        await log("[WAF] Skipped by ScopePolicy: {}".format(reason))
        return {"detected": False, "vendor": "ScopePolicy", "confidence": 0,
                "strategy": "passive_only", "blocked": True}
    result = {
        "detected":           False,
        "vendor":             "Unknown",
        "strategy":           "normal",
        "block_status":       0,
        "block_body":         "",
        "confidence":         0,
        "challenge_detected": False,   # v3.3: CAPTCHA / JS challenge flag
        "stage":              0,       # which stage confirmed the WAF
    }

    await log("[WAF] v3.3 fingerprinting — {}: benign probes first".format(base_url))
    base = base_url.rstrip("/")

    try:
        async with httpx.AsyncClient(
            headers=HEADERS, verify=False,
            follow_redirects=False, timeout=10
        ) as client:

            # ── Establish clean baseline ──────────────────────────────────────
            r_baseline = await client.get(
                base + "/burpollama-baseline-x9k2", headers=HEADERS
            )
            clean_status = r_baseline.status_code
            clean_body   = r_baseline.text[:300]
            throttle.calibrate_responses(
                base,
                normal_status=r_baseline.status_code,
                normal_body=r_baseline.text,
                normal_headers=dict(r_baseline.headers),
            )

            def calibrate_block(response: httpx.Response) -> None:
                throttle.calibrate_responses(
                    base,
                    normal_status=r_baseline.status_code,
                    normal_body=r_baseline.text,
                    normal_headers=dict(r_baseline.headers),
                    block_status=response.status_code,
                    block_body=response.text,
                    block_headers=dict(response.headers),
                )

            # ── Stage 1: Benign anomaly probes ────────────────────────────────
            for probe in BENIGN_ANOMALY_PROBES:
                try:
                    merged_headers = {**HEADERS, **probe["headers"]}
                    r = await client.request(
                        method  = probe["method"],
                        url     = base + probe["path"],
                        headers = merged_headers,
                        timeout = 6,
                    )
                    # Check for challenge page on any 200 response
                    if is_challenge_page(r):
                        result["challenge_detected"] = True
                        result["detected"]           = True
                        result["stage"]              = 1
                        result["block_status"]       = r.status_code
                        vendor, conf = _identify_vendor(r)
                        result.update({
                            "vendor":     vendor if conf > 0 else "WAF (challenge detected)",
                            "confidence": max(conf, 70),
                            "strategy":   _pick_strategy(vendor),
                            "block_body": r.text[:200],
                        })
                        await log("[WAF] Stage 1: Challenge page detected ({}) — {}".format(
                            probe["method"], result["vendor"]))
                        calibrate_block(r)
                        return result

                    # Response differs from clean baseline → WAF intercepted
                    if r.status_code != clean_status:
                        vendor, conf = _identify_vendor(r)
                        if conf >= 15:   # require some confidence before stopping
                            result.update({
                                "detected":     True,
                                "stage":        1,
                                "vendor":       vendor,
                                "confidence":   conf,
                                "block_status": r.status_code,
                                "strategy":     _pick_strategy(vendor),
                                "block_body":   r.text[:200],
                            })
                            await log("[WAF] Stage 1: {} detected ({}% conf, method={})".format(
                                vendor, conf, probe["method"]))
                            calibrate_block(r)
                            return result

                except httpx.RequestError:
                    pass

            # ── Stage 2: Malicious signature probes (only if Stage 1 missed) ─
            await log("[WAF] Stage 1 inconclusive — running Stage 2 signature probes")
            for probe_path in WAF_PROBE_PAYLOADS:
                try:
                    r = await client.get(base + probe_path, headers=HEADERS)

                    if is_challenge_page(r):
                        result.update({
                            "challenge_detected": True,
                            "detected":           True,
                            "stage":              2,
                            "block_status":       r.status_code,
                        })
                        vendor, conf = _identify_vendor(r)
                        result.update({
                            "vendor":     vendor if conf > 0 else "WAF (challenge)",
                            "confidence": max(conf, 65),
                            "strategy":   _pick_strategy(vendor),
                        })
                        await log("[WAF] Stage 2: Challenge page on probe {}".format(probe_path[:30]))
                        calibrate_block(r)
                        return result

                    if r.status_code != clean_status or r.text[:200] != clean_body[:200]:
                        vendor, conf = _identify_vendor(r)
                        if conf > 0:
                            result.update({
                                "detected":     True,
                                "stage":        2,
                                "vendor":       vendor,
                                "confidence":   conf,
                                "block_status": r.status_code,
                                "strategy":     _pick_strategy(vendor),
                                "block_body":   r.text[:300],
                            })
                            await log("[WAF] Stage 2: {} ({}%)".format(vendor, conf))
                            calibrate_block(r)
                            return result

                except httpx.RequestError:
                    pass

    except Exception as e:
        await log("[WAF] Fingerprint error: {}".format(e))

    if not result["detected"]:
        await log("[WAF] No WAF detected — normal strategy")
    return result
